# Generated by Django 5.0.3 on 2024-05-01 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_alter_user_phone_number'), ('users', '0003_alter_user_phone_number'), ('users', '0004_profile'), ('users', '0005_alter_profile_specialized_field'), ('users', '0006_alter_profile_user'), ('users', '0007_alter_profile_specialized_field'), ('users', '0008_review')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('category', models.TextField(choices=[('DR', 'doctor'), ('PT', 'patient')], max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialized_field', models.TextField(choices=[('EY', 'opthamologist'), ('ENT', 'otolaryngologist'), ('SK', 'dermatologist'), ('DT', 'dentist'), ('BN', 'physiotherapist'), ('PN', 'physician'), ('UTI', 'urologist'), ('SOI', 'gynecologist')])),
                ('doctor_type', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('meet', models.ManyToManyField(blank=True, related_name='meets', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('stars', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
