# Generated by Django 4.2.4 on 2024-09-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_api_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.TextField(choices=[('DR', 'doctor'), ('PT', 'patient'), ('API', 'api user')], max_length=20),
        ),
    ]
