# Generated by Django 4.2.4 on 2024-09-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_apiuser_alter_user_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor_type',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialized_field',
            field=models.CharField(),
        ),
    ]
