# Generated by Django 4.2.4 on 2024-09-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_doctor_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='doctor_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='patient_type',
            field=models.CharField(choices=[('PT', 'Preteen'), ('TN', 'Teenager'), ('AD', 'Adult'), ('OAD', 'Old Adult')], default='PT'),
        ),
    ]
