# Generated by Django 4.2.4 on 2024-09-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_profile_doctor_type_profile_patient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='patient_type',
            field=models.CharField(choices=[('PT', 'Preteen'), ('TN', 'Teenager'), ('AD', 'Adult'), ('OAD', 'Old Adult')]),
        ),
    ]
