# Generated by Django 4.2.4 on 2024-09-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_patient_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='specialized_field',
            new_name='specialization',
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
