# Generated by Django 4.2.4 on 2024-09-24 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_specialized_field_profile_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='meet',
        ),
        migrations.AddField(
            model_name='profile',
            name='meets',
            field=models.ManyToManyField(blank=True, related_name='meets_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
