# Generated by Django 4.2.4 on 2025-03-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='meets',
        ),
    ]
