# Generated by Django 4.2.4 on 2025-03-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('PT', 'Preteen'), ('TN', 'Teenager'), ('AD', 'Adult'), ('OAD', 'Old Adult')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
