# Generated by Django 4.2.4 on 2025-05-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_profile_patient_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIUser',
        ),
    ]
