# Generated by Django 4.2.4 on 2025-06-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_delete_apiuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.TextField(choices=[('DR', 'doctor'), ('PT', 'patient')], max_length=20),
        ),
    ]
