# Generated by Django 5.0.3 on 2024-04-25 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('booking', '0001_initial'), ('booking', '0002_alter_illnessdetail_body_part_and_more'), ('booking', '0003_alter_illnessdetail_age'), ('booking', '0004_illnessdetail_date_created'), ('booking', '0005_remove_illnessdetail_date_created_and_more'), ('booking', '0006_alter_illnessdetail_created_at'), ('booking', '0007_alter_illnessdetail_created_at'), ('booking', '0008_alter_illnessdetail_patient'), ('booking', '0009_illness_delete_illnessdetail'), ('booking', '0010_appointment'), ('booking', '0011_alter_appointment_created_at'), ('booking', '0012_alter_appointment_owner_alter_appointment_patient'), ('booking', '0013_alter_appointment_patient')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(blank=True, choices=[('EY', 'eye'), ('ER', 'ear'), ('NS', 'nose'), ('SK', 'skin'), ('DT', 'mouth&dental'), ('BN', 'bone')], null=True)),
                ('specific_illness', models.CharField(blank=True, choices=[('ML', 'malaria'), ('TY', 'typhoid'), ('DB', 'diabetes'), ('UTI', 'urinary tract infection'), ('SOI', 'sex organ illness')], null=True)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illness', to=settings.AUTH_USER_MODEL)),
                ('treated_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='illness_treated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField()),
                ('date_of_appointment', models.DateField()),
                ('time_of_appointment', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_booked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
