# Generated by Django 5.0.3 on 2024-03-25 00:57

import django.db.models.deletion
from django.conf import settings
# Generated by Django 5.0.3 on 2024-03-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IllnessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(blank=True, choices=[('EY', 'eye'), ('ER', 'ear'), ('NS', 'nose'), ('SK', 'skin'), ('DT', 'mouth&dental'), ('BN', 'bone')], null=True)),
                ('illness', models.CharField(blank=True, choices=[('ML', 'malaria'), ('TY', 'typhoid'), ('DB', 'diabetes'), ('UTI', 'urinary tract infection'), ('SOI', 'sex organ illness')], null=True)),
                ('age', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
