# Generated by Django 5.0.3 on 2024-03-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IllnessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(blank=True, choices=[('EY', 'eye'), ('ER', 'ear'), ('NS', 'nose'), ('SK', 'skin'), ('DT', 'mouth&dental'), ('BN', 'bone')], default='EY', null=True)),
                ('illness', models.CharField(blank=True, choices=[('ML', 'malaria'), ('TY', 'typhoid'), ('DB', 'diabetes'), ('UTI', 'urinary tract infection'), ('SOI', 'sex organ illness')], default='ML', null=True)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
