<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-03-25 00:57

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.0.3 on 2024-03-19 20:26

>>>>>>> b5226b73865f906e807fa007932ebc7913abee36
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> b5226b73865f906e807fa007932ebc7913abee36
    ]

    operations = [
        migrations.CreateModel(
            name='IllnessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('body_part', models.CharField(blank=True, choices=[('EY', 'eye'), ('ER', 'ear'), ('NS', 'nose'), ('SK', 'skin'), ('DT', 'mouth&dental'), ('BN', 'bone')], null=True)),
                ('illness', models.CharField(blank=True, choices=[('ML', 'malaria'), ('TY', 'typhoid'), ('DB', 'diabetes'), ('UTI', 'urinary tract infection'), ('SOI', 'sex organ illness')], null=True)),
                ('age', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
=======
                ('body_part', models.CharField(blank=True, choices=[('EY', 'eye'), ('ER', 'ear'), ('NS', 'nose'), ('SK', 'skin'), ('DT', 'mouth&dental'), ('BN', 'bone')], default='EY', null=True)),
                ('illness', models.CharField(blank=True, choices=[('ML', 'malaria'), ('TY', 'typhoid'), ('DB', 'diabetes'), ('UTI', 'urinary tract infection'), ('SOI', 'sex organ illness')], default='ML', null=True)),
                ('age', models.IntegerField(default=0)),
>>>>>>> b5226b73865f906e807fa007932ebc7913abee36
            ],
        ),
    ]
