# Generated by Django 5.0.3 on 2024-03-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_illnessdetail_body_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illnessdetail',
            name='age',
            field=models.IntegerField(),
        ),
    ]
