# Generated by Django 5.0.3 on 2024-03-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_illnessdetail_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='illnessdetail',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_created'),
        ),
    ]
