# Generated by Django 5.0.3 on 2024-03-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_illnessdetail_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illnessdetail',
            name='date_created',
        ),
        migrations.AddField(
            model_name='illnessdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at'),
        ),
    ]
