# Generated by Django 5.0.3 on 2024-03-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_illnessdetail_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illnessdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
    ]
