# Generated by Django 5.0.3 on 2024-04-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_appointment_owner_alter_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.CharField(),
        ),
    ]
