# Generated by Django 5.0.3 on 2024-04-25 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_appointment_patient'),
        ('users', '0007_alter_profile_specialized_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_booked', to='users.profile'),
        ),
    ]
