# Generated by Django 4.2.4 on 2024-09-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_remove_illness_age_illness_age_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(unique=True)),
                ('Name', models.CharField()),
            ],
        ),
    ]
