# Generated by Django 4.2.4 on 2024-09-21 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0018_symptom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], null=True)),
                ('year_of_birth', models.IntegerField(blank=True, null=True)),
                ('age_group', models.CharField(choices=[('PT', 'Preteen'), ('TN', 'Teenager'), ('AD', 'Adult'), ('OAD', 'Old Adult')], default='PT')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illness', to=settings.AUTH_USER_MODEL)),
                ('symptoms', models.ManyToManyField(blank=True, related_name='complaints', to='booking.symptom')),
                ('treated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='illness_treated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Illness',
        ),
    ]
