# Generated by Django 4.2.4 on 2024-10-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_profile_slug'),
        ('booking', '0021_alter_complaint_sex_alter_complaint_year_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='treated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='illness_treated', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='Name',
            field=models.CharField(max_length=225),
        ),
    ]
