# Generated by Django 4.2.4 on 2025-03-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_meet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
