# Generated by Django 4.2.4 on 2025-03-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_alter_meet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='ID',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
