# Generated by Django 4.2.4 on 2025-03-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_alter_meet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='ID',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
