# Generated by Django 4.2.4 on 2025-05-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_alter_meet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='ID',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='Name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
