# Generated by Django 4.2.4 on 2025-05-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_alter_symptom_id_alter_symptom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='ID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='Name',
            field=models.CharField(max_length=225),
        ),
    ]
