# Generated by Django 4.2.4 on 2025-06-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_alter_symptom_id_alter_symptom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='complaint',
            name='symptom',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
